####### Mode selection flags for EFTCAMB  #######

#	 EFT flags: set up in which mode EFTCAMB is used.
# 	 We refer to the documentation (EFTCAMB:numerical notes) for a thorough
# 	 explanation of the effect of these flags.
#
# 1) Main EFT flag:
#      EFTflag = 0 : GR code. Every EFT modification is ignored.
#      EFTflag = 1 : Pure EFT code.
#      EFTflag = 2 : EFT alternative parametrizations.
#      EFTflag = 3 : designer mapping EFT.
#      EFTflag = 4 : full EFT mapping.

EFTflag = 4

# 2) Pure EFT model selection flag:
#      PureEFTmodel = 1 : standard pure EFT with 7 EFT functions and w_DE. Relevant if EFTflag = 1.

; PureEFTmodel = 1

# 3) EFT alternative parametrizations model selection flag. Relevant if EFTflag = 2.
#
#      AltParEFTmodel = 1 : reparametrized Horndeski (RPH)

; AltParEFTmodel = 1

# 4) Designer mapping EFT model selection flag. Relevant if EFTflag = 3.
#
#      DesignerEFTmodel = 1 : designer f(R)
#      DesignerEFTmodel = 2 : designer minimally coupled quintessence

; DesignerEFTmodel = 1

# 5) Full mapping EFT model selection flag. Relevant if EFTflag = 4.
#
#      FullMappingEFTmodel = 1 : Horava gravity
#      FullMappingEFTmodel = 3 : Kmouflage

FullMappingEFTmodel = 5

Omega_model  = 3    
Lambda_model = 2

Omega_Pade_order_N = 1
Omega_Pade_order_D = 1

Omegaa0= 1
; OmegaN0 = 6.10789463e-02
OmegaN0 = 0
; OmegaN1 = -1.07796270e-01
OmegaN1 = 0.2
OmegaD1 = 0.7
OmegaN2 = 3.55214592e-01
OmegaN3 = -6.90860633e-01
OmegaN4 = -9.61186562e-01
OmegaN5 = 4.80381618e-01
OmegaD1 = -2.71984704e-01
OmegaD2 = -3.31038524e-01
OmegaD3 = -6.70314664e-01
OmegaD4 = -6.63316713e-01
; OmegaN0_min = -1
; OmegaN1_min = -1
; OmegaN2_min = -1
; OmegaN3_min = -1
; OmegaN4_min = -1
; OmegaN5_min = -1
; OmegaD1_min = -1
; OmegaD2_min = -1
; OmegaD3_min = -1
; OmegaD4_min = -1

; OmegaN0_max = 1
; OmegaN1_max = 1
; OmegaN2_max = 1
; OmegaN3_max = 1
; OmegaN4_max = 1
; OmegaN5_max = 1
; OmegaD1_max = 1
; OmegaD2_max = 1
; OmegaD3_max = 1
; OmegaD4_max = 1

Lambda_Pade_order_N = 5
Lambda_Pade_order_D = 4
Lambda_Taylor_order = 1

Lambdaa0 = 1
Lambda0 = 0.3
Lambda1 = 1.0
; LambdaN0 = 6.52551307e-01
; LambdaN0 = 0
LambdaN1 = 1.51683685e-02
LambdaN2 = 9.33583835e-01
LambdaN3 = -4.12694082e-01
LambdaN4 = 7.65527834e-01
LambdaN5 = 6.47642432e-01
LambdaD1 = 8.81083979e-01
LambdaD2 = 4.78872165e-01
LambdaD3 = 9.79742290e-01
LambdaD4 = 9.26771306e-01
; LambdaN0_min = -1
; LambdaN1_min = -1
; LambdaN2_min = -1
; LambdaN3_min = -1
; LambdaN4_min = -1
; LambdaN5_min = -1
; LambdaD1_min = -1
; LambdaD2_min = -1
; LambdaD3_min = -1
; LambdaD4_min = -1

; LambdaN0_max = 1
; LambdaN1_max = 1
; LambdaN2_max = 1
; LambdaN3_max = 1
; LambdaN4_max = 1
; LambdaN5_max = 1
; LambdaD1_max = 1
; LambdaD2_max = 1
; LambdaD3_max = 1
; LambdaD4_max = 1

EFTCAMB_stability_time = 0.1

; sampler_number = 10000

####### Model selection flags for EFTCAMB #######

# 1) Std. Pure EFT model selection flag.
#	 The following structure applies to every operator and can be specified for every operator
#	 separately. Relevant if EFTflag = 1 and PureEFTmodel = 1.
#
#      PureEFTmodel___ = 0 : Zero (operator ignored)
#      PureEFTmodel___ = 1 : Constant model
#      PureEFTmodel___ = 2 : Linear model
#      PureEFTmodel___ = 3 : Power law model
#      PureEFTmodel___ = 4 : Exponential model
#      PureEFTmodel___ = 5 : User defined

; PureEFTmodelOmega  = 2
; PureEFTmodelGamma1 = 0
; PureEFTmodelGamma2 = 0
; PureEFTmodelGamma3 = 0
; PureEFTmodelGamma4 = 0
; PureEFTmodelGamma5 = 0
; PureEFTmodelGamma6 = 0

# 2) Pure EFT Horndeski: Restricts pure EFT models to Horndeski. Relevant if EFTflag = 1 and PureEFTmodel = 1.
#    Pure EFT choices for gamma_4, gamma_5, gamma_6 will be ignored and handled internally according to the Horndeski condition.

; PureEFTHorndeski = F

# 3) w_DE model selection flag. Relevant for all the models where the expansion history
#    can be choosen.
#      EFTwDE = 0 : Cosmological constant
#      EFTwDE = 1 : DE with constant Eos determined by EFTw0
#      EFTwDE = 2 : CPL parametrization
#      EFTwDE = 3 : JBP parametrization
#      EFTwDE = 4 : turning point parametrization
#      EFTwDE = 5 : Taylor expansion
#      EFTwDE = 6 : User defined

; EFTwDE = 0

# 4) RPH model selection: select a model for the RPH functions. Relevant if EFTflag = 2 and AltParEFTmodel = 1.
#
#      RPH___model = 0 : Zero (function ignored)
#      RPH___model = 1 : Constant model
#      RPH___model = 2 : Linear model
#      RPH___model = 3 : Power Law model
#      RPH___model = 4 : User defined

; RPHmassPmodel      = 0
; RPHkineticitymodel = 0
; RPHbraidingmodel   = 0
; RPHtensormodel     = 0

# 5) Horava Solar System: Restricts Horava models to the sub-class which evades Solar System constraints.
#    Relevant only if EFTflag = 4 and FullMappingEFTmodel = 1.
#    Choices for Horava_xi will be automatically ignored.

; HoravaSolarSystem = F

####### Stability conditions flags        #######

# 1) enforces the mathematical stability of the scalar field equation.
EFT_mathematical_stability = F

# 2) enforces the ghost viability of the model.
EFT_ghost_stability     = T

# 3) enforces the physical viability of the model.
EFT_gradient_stability     = T

# 4) enforces the mass viability of the model.
EFT_mass_stability     = F

# 5) Additional priors on cosmological parameters. For more informations read the related section in the notes.
#    These conditions are model specific.
EFT_additional_priors        = T

####### Model parameters for EFTCAMB #######

#	Notice that if the model is not selected via the model selection flags then
#	the values of the parameters are automatically ignored.

#  1) Background Dark Energy equation of state parameters:

EFTw0  = -1.0
EFTwa  = 0.0
EFTwn  = 2
EFTwat = 0.8
EFtw2  = 0.1
EFTw3  = 0.1

#  2) Pure EFT parameters:

EFTOmega0 = 0.1
EFTOmegaExp = 1.0

EFTGamma10 = 0
EFTGamma1Exp = 0

EFTGamma20 = 0.1
EFTGamma2Exp = 0

EFTGamma30 = 0.001
EFTGamma3Exp = 0

EFTGamma40 = 0.001
EFTGamma4Exp = 0

EFTGamma50 = 0.1
EFTGamma5Exp = 0

EFTGamma60 = 0.1
EFTGamma6Exp = 0

#  3) Designer mapping parameters:
#      	 Model 1: designer f(R) theories

EFTB0 = 0.1

#  4) EFT alternative parametrizations parameters:
#      	 Model 1: reparametrized Horndeski (RPH)

RPHmassP0        = 0.1
RPHmassPexp      = 0

RPHkineticity0   = 0.1
RPHkineticityexp = 0

RPHbraiding0     = 0.1
RPHbraidingexp   = 0

RPHtensor0       = 0.1
RPHtensorexp     = 0

# 5) Full mapping parameters:
#      	 Model 1: Horava gravity

Horava_xi      = 0.0
Horava_lambda  = 0.0
Horava_eta     = 0.0

# 5) Full mapping parameters:
#      	 Model 3: K-mouflage

Kmimic = F

alphaU        = 0.4
gammaU        = 1.
m             = 3.
eps2_0        = -0.04
gammaA        = 0.2

EFTCAMB_turn_on_time = 1.e-8
file_root = hsamp_00016
